// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: cometbft/services/pruning/v1/pruning.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

/** SetBlockRetainHeightRequest sets the retain height for blocks. */
export interface SetBlockRetainHeightRequest {
  height: string;
}

/** SetBlockRetainHeightResponse is empty. */
export interface SetBlockRetainHeightResponse {
}

/** GetBlockRetainHeightRequest is a request for the retain height. */
export interface GetBlockRetainHeightRequest {
}

/** GetBlockRetainHeightResponse returns the retain height for blocks. */
export interface GetBlockRetainHeightResponse {
  /** The retain height set by the application. */
  app_retain_height: string;
  /**
   * The retain height set via the pruning service (e.g. by the data
   * companion) specifically for blocks.
   */
  pruning_service_retain_height: string;
}

/** SetBlockResultsRetainHeightRequest sets the retain height for block results. */
export interface SetBlockResultsRetainHeightRequest {
  height: string;
}

/** SetBlockResultsRetainHeightResponse is empty. */
export interface SetBlockResultsRetainHeightResponse {
}

/** GetBlockResultsRetainHeightRequest is a request for the retain height. */
export interface GetBlockResultsRetainHeightRequest {
}

/** GetBlockResultsRetainHeightResponse returns the retain height for block results. */
export interface GetBlockResultsRetainHeightResponse {
  /**
   * The retain height set by the pruning service (e.g. by the data
   * companion) specifically for block results.
   */
  pruning_service_retain_height: string;
}

/** SetTxIndexerRetainHeightRequest sets the retain height for the tx indexer. */
export interface SetTxIndexerRetainHeightRequest {
  height: string;
}

/** SetTxIndexerRetainHeightResponse is empty. */
export interface SetTxIndexerRetainHeightResponse {
}

/** GetTxIndexerRetainHeightRequest is a request for the retain height. */
export interface GetTxIndexerRetainHeightRequest {
}

/** GetTxIndexerRetainHeightResponse returns the retain height for the tx indexer. */
export interface GetTxIndexerRetainHeightResponse {
  height: string;
}

/** SetBlockIndexerRetainHeightRequest sets the retain height for the block indexer. */
export interface SetBlockIndexerRetainHeightRequest {
  height: string;
}

/** SetBlockIndexerRetainHeightResponse is empty. */
export interface SetBlockIndexerRetainHeightResponse {
}

/** GetBlockIndexerRetainHeightRequest is a request for the retain height. */
export interface GetBlockIndexerRetainHeightRequest {
}

/** GetBlockIndexerRetainHeightResponse returns the retain height for the block indexer. */
export interface GetBlockIndexerRetainHeightResponse {
  height: string;
}

function createBaseSetBlockRetainHeightRequest(): SetBlockRetainHeightRequest {
  return { height: "0" };
}

export const SetBlockRetainHeightRequest = {
  $type: "cometbft.services.pruning.v1.SetBlockRetainHeightRequest" as const,

  encode(message: SetBlockRetainHeightRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.height !== "0") {
      writer.uint32(8).uint64(message.height);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetBlockRetainHeightRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetBlockRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.height = longToString(reader.uint64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetBlockRetainHeightRequest {
    return { height: isSet(object.height) ? globalThis.String(object.height) : "0" };
  },

  toJSON(message: SetBlockRetainHeightRequest): unknown {
    const obj: any = {};
    if (message.height !== undefined) {
      obj.height = message.height;
    }
    return obj;
  },

  create(base?: DeepPartial<SetBlockRetainHeightRequest>): SetBlockRetainHeightRequest {
    return SetBlockRetainHeightRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetBlockRetainHeightRequest>): SetBlockRetainHeightRequest {
    const message = createBaseSetBlockRetainHeightRequest();
    message.height = object.height ?? "0";
    return message;
  },
};

function createBaseSetBlockRetainHeightResponse(): SetBlockRetainHeightResponse {
  return {};
}

export const SetBlockRetainHeightResponse = {
  $type: "cometbft.services.pruning.v1.SetBlockRetainHeightResponse" as const,

  encode(_: SetBlockRetainHeightResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetBlockRetainHeightResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetBlockRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetBlockRetainHeightResponse {
    return {};
  },

  toJSON(_: SetBlockRetainHeightResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<SetBlockRetainHeightResponse>): SetBlockRetainHeightResponse {
    return SetBlockRetainHeightResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<SetBlockRetainHeightResponse>): SetBlockRetainHeightResponse {
    const message = createBaseSetBlockRetainHeightResponse();
    return message;
  },
};

function createBaseGetBlockRetainHeightRequest(): GetBlockRetainHeightRequest {
  return {};
}

export const GetBlockRetainHeightRequest = {
  $type: "cometbft.services.pruning.v1.GetBlockRetainHeightRequest" as const,

  encode(_: GetBlockRetainHeightRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetBlockRetainHeightRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetBlockRetainHeightRequest {
    return {};
  },

  toJSON(_: GetBlockRetainHeightRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<GetBlockRetainHeightRequest>): GetBlockRetainHeightRequest {
    return GetBlockRetainHeightRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetBlockRetainHeightRequest>): GetBlockRetainHeightRequest {
    const message = createBaseGetBlockRetainHeightRequest();
    return message;
  },
};

function createBaseGetBlockRetainHeightResponse(): GetBlockRetainHeightResponse {
  return { app_retain_height: "0", pruning_service_retain_height: "0" };
}

export const GetBlockRetainHeightResponse = {
  $type: "cometbft.services.pruning.v1.GetBlockRetainHeightResponse" as const,

  encode(message: GetBlockRetainHeightResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.app_retain_height !== "0") {
      writer.uint32(8).uint64(message.app_retain_height);
    }
    if (message.pruning_service_retain_height !== "0") {
      writer.uint32(16).uint64(message.pruning_service_retain_height);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetBlockRetainHeightResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.app_retain_height = longToString(reader.uint64() as Long);
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.pruning_service_retain_height = longToString(reader.uint64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBlockRetainHeightResponse {
    return {
      app_retain_height: isSet(object.app_retain_height) ? globalThis.String(object.app_retain_height) : "0",
      pruning_service_retain_height: isSet(object.pruning_service_retain_height)
        ? globalThis.String(object.pruning_service_retain_height)
        : "0",
    };
  },

  toJSON(message: GetBlockRetainHeightResponse): unknown {
    const obj: any = {};
    if (message.app_retain_height !== undefined) {
      obj.app_retain_height = message.app_retain_height;
    }
    if (message.pruning_service_retain_height !== undefined) {
      obj.pruning_service_retain_height = message.pruning_service_retain_height;
    }
    return obj;
  },

  create(base?: DeepPartial<GetBlockRetainHeightResponse>): GetBlockRetainHeightResponse {
    return GetBlockRetainHeightResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetBlockRetainHeightResponse>): GetBlockRetainHeightResponse {
    const message = createBaseGetBlockRetainHeightResponse();
    message.app_retain_height = object.app_retain_height ?? "0";
    message.pruning_service_retain_height = object.pruning_service_retain_height ?? "0";
    return message;
  },
};

function createBaseSetBlockResultsRetainHeightRequest(): SetBlockResultsRetainHeightRequest {
  return { height: "0" };
}

export const SetBlockResultsRetainHeightRequest = {
  $type: "cometbft.services.pruning.v1.SetBlockResultsRetainHeightRequest" as const,

  encode(message: SetBlockResultsRetainHeightRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.height !== "0") {
      writer.uint32(8).uint64(message.height);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetBlockResultsRetainHeightRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetBlockResultsRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.height = longToString(reader.uint64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetBlockResultsRetainHeightRequest {
    return { height: isSet(object.height) ? globalThis.String(object.height) : "0" };
  },

  toJSON(message: SetBlockResultsRetainHeightRequest): unknown {
    const obj: any = {};
    if (message.height !== undefined) {
      obj.height = message.height;
    }
    return obj;
  },

  create(base?: DeepPartial<SetBlockResultsRetainHeightRequest>): SetBlockResultsRetainHeightRequest {
    return SetBlockResultsRetainHeightRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetBlockResultsRetainHeightRequest>): SetBlockResultsRetainHeightRequest {
    const message = createBaseSetBlockResultsRetainHeightRequest();
    message.height = object.height ?? "0";
    return message;
  },
};

function createBaseSetBlockResultsRetainHeightResponse(): SetBlockResultsRetainHeightResponse {
  return {};
}

export const SetBlockResultsRetainHeightResponse = {
  $type: "cometbft.services.pruning.v1.SetBlockResultsRetainHeightResponse" as const,

  encode(_: SetBlockResultsRetainHeightResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetBlockResultsRetainHeightResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetBlockResultsRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetBlockResultsRetainHeightResponse {
    return {};
  },

  toJSON(_: SetBlockResultsRetainHeightResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<SetBlockResultsRetainHeightResponse>): SetBlockResultsRetainHeightResponse {
    return SetBlockResultsRetainHeightResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<SetBlockResultsRetainHeightResponse>): SetBlockResultsRetainHeightResponse {
    const message = createBaseSetBlockResultsRetainHeightResponse();
    return message;
  },
};

function createBaseGetBlockResultsRetainHeightRequest(): GetBlockResultsRetainHeightRequest {
  return {};
}

export const GetBlockResultsRetainHeightRequest = {
  $type: "cometbft.services.pruning.v1.GetBlockResultsRetainHeightRequest" as const,

  encode(_: GetBlockResultsRetainHeightRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetBlockResultsRetainHeightRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockResultsRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetBlockResultsRetainHeightRequest {
    return {};
  },

  toJSON(_: GetBlockResultsRetainHeightRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<GetBlockResultsRetainHeightRequest>): GetBlockResultsRetainHeightRequest {
    return GetBlockResultsRetainHeightRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetBlockResultsRetainHeightRequest>): GetBlockResultsRetainHeightRequest {
    const message = createBaseGetBlockResultsRetainHeightRequest();
    return message;
  },
};

function createBaseGetBlockResultsRetainHeightResponse(): GetBlockResultsRetainHeightResponse {
  return { pruning_service_retain_height: "0" };
}

export const GetBlockResultsRetainHeightResponse = {
  $type: "cometbft.services.pruning.v1.GetBlockResultsRetainHeightResponse" as const,

  encode(message: GetBlockResultsRetainHeightResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.pruning_service_retain_height !== "0") {
      writer.uint32(8).uint64(message.pruning_service_retain_height);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetBlockResultsRetainHeightResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockResultsRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.pruning_service_retain_height = longToString(reader.uint64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBlockResultsRetainHeightResponse {
    return {
      pruning_service_retain_height: isSet(object.pruning_service_retain_height)
        ? globalThis.String(object.pruning_service_retain_height)
        : "0",
    };
  },

  toJSON(message: GetBlockResultsRetainHeightResponse): unknown {
    const obj: any = {};
    if (message.pruning_service_retain_height !== undefined) {
      obj.pruning_service_retain_height = message.pruning_service_retain_height;
    }
    return obj;
  },

  create(base?: DeepPartial<GetBlockResultsRetainHeightResponse>): GetBlockResultsRetainHeightResponse {
    return GetBlockResultsRetainHeightResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetBlockResultsRetainHeightResponse>): GetBlockResultsRetainHeightResponse {
    const message = createBaseGetBlockResultsRetainHeightResponse();
    message.pruning_service_retain_height = object.pruning_service_retain_height ?? "0";
    return message;
  },
};

function createBaseSetTxIndexerRetainHeightRequest(): SetTxIndexerRetainHeightRequest {
  return { height: "0" };
}

export const SetTxIndexerRetainHeightRequest = {
  $type: "cometbft.services.pruning.v1.SetTxIndexerRetainHeightRequest" as const,

  encode(message: SetTxIndexerRetainHeightRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.height !== "0") {
      writer.uint32(8).uint64(message.height);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetTxIndexerRetainHeightRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTxIndexerRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.height = longToString(reader.uint64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetTxIndexerRetainHeightRequest {
    return { height: isSet(object.height) ? globalThis.String(object.height) : "0" };
  },

  toJSON(message: SetTxIndexerRetainHeightRequest): unknown {
    const obj: any = {};
    if (message.height !== undefined) {
      obj.height = message.height;
    }
    return obj;
  },

  create(base?: DeepPartial<SetTxIndexerRetainHeightRequest>): SetTxIndexerRetainHeightRequest {
    return SetTxIndexerRetainHeightRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetTxIndexerRetainHeightRequest>): SetTxIndexerRetainHeightRequest {
    const message = createBaseSetTxIndexerRetainHeightRequest();
    message.height = object.height ?? "0";
    return message;
  },
};

function createBaseSetTxIndexerRetainHeightResponse(): SetTxIndexerRetainHeightResponse {
  return {};
}

export const SetTxIndexerRetainHeightResponse = {
  $type: "cometbft.services.pruning.v1.SetTxIndexerRetainHeightResponse" as const,

  encode(_: SetTxIndexerRetainHeightResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetTxIndexerRetainHeightResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTxIndexerRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetTxIndexerRetainHeightResponse {
    return {};
  },

  toJSON(_: SetTxIndexerRetainHeightResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<SetTxIndexerRetainHeightResponse>): SetTxIndexerRetainHeightResponse {
    return SetTxIndexerRetainHeightResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<SetTxIndexerRetainHeightResponse>): SetTxIndexerRetainHeightResponse {
    const message = createBaseSetTxIndexerRetainHeightResponse();
    return message;
  },
};

function createBaseGetTxIndexerRetainHeightRequest(): GetTxIndexerRetainHeightRequest {
  return {};
}

export const GetTxIndexerRetainHeightRequest = {
  $type: "cometbft.services.pruning.v1.GetTxIndexerRetainHeightRequest" as const,

  encode(_: GetTxIndexerRetainHeightRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetTxIndexerRetainHeightRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTxIndexerRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetTxIndexerRetainHeightRequest {
    return {};
  },

  toJSON(_: GetTxIndexerRetainHeightRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<GetTxIndexerRetainHeightRequest>): GetTxIndexerRetainHeightRequest {
    return GetTxIndexerRetainHeightRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetTxIndexerRetainHeightRequest>): GetTxIndexerRetainHeightRequest {
    const message = createBaseGetTxIndexerRetainHeightRequest();
    return message;
  },
};

function createBaseGetTxIndexerRetainHeightResponse(): GetTxIndexerRetainHeightResponse {
  return { height: "0" };
}

export const GetTxIndexerRetainHeightResponse = {
  $type: "cometbft.services.pruning.v1.GetTxIndexerRetainHeightResponse" as const,

  encode(message: GetTxIndexerRetainHeightResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.height !== "0") {
      writer.uint32(8).uint64(message.height);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetTxIndexerRetainHeightResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTxIndexerRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.height = longToString(reader.uint64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTxIndexerRetainHeightResponse {
    return { height: isSet(object.height) ? globalThis.String(object.height) : "0" };
  },

  toJSON(message: GetTxIndexerRetainHeightResponse): unknown {
    const obj: any = {};
    if (message.height !== undefined) {
      obj.height = message.height;
    }
    return obj;
  },

  create(base?: DeepPartial<GetTxIndexerRetainHeightResponse>): GetTxIndexerRetainHeightResponse {
    return GetTxIndexerRetainHeightResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetTxIndexerRetainHeightResponse>): GetTxIndexerRetainHeightResponse {
    const message = createBaseGetTxIndexerRetainHeightResponse();
    message.height = object.height ?? "0";
    return message;
  },
};

function createBaseSetBlockIndexerRetainHeightRequest(): SetBlockIndexerRetainHeightRequest {
  return { height: "0" };
}

export const SetBlockIndexerRetainHeightRequest = {
  $type: "cometbft.services.pruning.v1.SetBlockIndexerRetainHeightRequest" as const,

  encode(message: SetBlockIndexerRetainHeightRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.height !== "0") {
      writer.uint32(8).uint64(message.height);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetBlockIndexerRetainHeightRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetBlockIndexerRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.height = longToString(reader.uint64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetBlockIndexerRetainHeightRequest {
    return { height: isSet(object.height) ? globalThis.String(object.height) : "0" };
  },

  toJSON(message: SetBlockIndexerRetainHeightRequest): unknown {
    const obj: any = {};
    if (message.height !== undefined) {
      obj.height = message.height;
    }
    return obj;
  },

  create(base?: DeepPartial<SetBlockIndexerRetainHeightRequest>): SetBlockIndexerRetainHeightRequest {
    return SetBlockIndexerRetainHeightRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetBlockIndexerRetainHeightRequest>): SetBlockIndexerRetainHeightRequest {
    const message = createBaseSetBlockIndexerRetainHeightRequest();
    message.height = object.height ?? "0";
    return message;
  },
};

function createBaseSetBlockIndexerRetainHeightResponse(): SetBlockIndexerRetainHeightResponse {
  return {};
}

export const SetBlockIndexerRetainHeightResponse = {
  $type: "cometbft.services.pruning.v1.SetBlockIndexerRetainHeightResponse" as const,

  encode(_: SetBlockIndexerRetainHeightResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetBlockIndexerRetainHeightResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetBlockIndexerRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetBlockIndexerRetainHeightResponse {
    return {};
  },

  toJSON(_: SetBlockIndexerRetainHeightResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<SetBlockIndexerRetainHeightResponse>): SetBlockIndexerRetainHeightResponse {
    return SetBlockIndexerRetainHeightResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<SetBlockIndexerRetainHeightResponse>): SetBlockIndexerRetainHeightResponse {
    const message = createBaseSetBlockIndexerRetainHeightResponse();
    return message;
  },
};

function createBaseGetBlockIndexerRetainHeightRequest(): GetBlockIndexerRetainHeightRequest {
  return {};
}

export const GetBlockIndexerRetainHeightRequest = {
  $type: "cometbft.services.pruning.v1.GetBlockIndexerRetainHeightRequest" as const,

  encode(_: GetBlockIndexerRetainHeightRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetBlockIndexerRetainHeightRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockIndexerRetainHeightRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetBlockIndexerRetainHeightRequest {
    return {};
  },

  toJSON(_: GetBlockIndexerRetainHeightRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<GetBlockIndexerRetainHeightRequest>): GetBlockIndexerRetainHeightRequest {
    return GetBlockIndexerRetainHeightRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetBlockIndexerRetainHeightRequest>): GetBlockIndexerRetainHeightRequest {
    const message = createBaseGetBlockIndexerRetainHeightRequest();
    return message;
  },
};

function createBaseGetBlockIndexerRetainHeightResponse(): GetBlockIndexerRetainHeightResponse {
  return { height: "0" };
}

export const GetBlockIndexerRetainHeightResponse = {
  $type: "cometbft.services.pruning.v1.GetBlockIndexerRetainHeightResponse" as const,

  encode(message: GetBlockIndexerRetainHeightResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.height !== "0") {
      writer.uint32(8).uint64(message.height);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetBlockIndexerRetainHeightResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockIndexerRetainHeightResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.height = longToString(reader.uint64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBlockIndexerRetainHeightResponse {
    return { height: isSet(object.height) ? globalThis.String(object.height) : "0" };
  },

  toJSON(message: GetBlockIndexerRetainHeightResponse): unknown {
    const obj: any = {};
    if (message.height !== undefined) {
      obj.height = message.height;
    }
    return obj;
  },

  create(base?: DeepPartial<GetBlockIndexerRetainHeightResponse>): GetBlockIndexerRetainHeightResponse {
    return GetBlockIndexerRetainHeightResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetBlockIndexerRetainHeightResponse>): GetBlockIndexerRetainHeightResponse {
    const message = createBaseGetBlockIndexerRetainHeightResponse();
    message.height = object.height ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToString(long: Long) {
  return long.toString();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
