// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: cometbft/mempool/v2/types.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

/** Txs contains a list of transaction from the mempool. */
export interface Txs {
  txs: Uint8Array[];
}

/**
 * HaveTx is sent by the DOG protocol to signal a peer that the sender already
 * has a transaction.
 */
export interface HaveTx {
  tx_key: Uint8Array;
}

/**
 * ResetRoute is sent by the DOG protocol to signal a peer to reset a (random)
 * route to the sender.
 */
export interface ResetRoute {
}

/** Message is an abstract mempool message. */
export interface Message {
  txs?: Txs | undefined;
  have_tx?: HaveTx | undefined;
  reset_route?: ResetRoute | undefined;
}

function createBaseTxs(): Txs {
  return { txs: [] };
}

export const Txs = {
  $type: "cometbft.mempool.v2.Txs" as const,

  encode(message: Txs, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.txs) {
      writer.uint32(10).bytes(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Txs {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTxs();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.txs.push(reader.bytes());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Txs {
    return { txs: globalThis.Array.isArray(object?.txs) ? object.txs.map((e: any) => bytesFromBase64(e)) : [] };
  },

  toJSON(message: Txs): unknown {
    const obj: any = {};
    if (message.txs?.length) {
      obj.txs = message.txs.map((e) => base64FromBytes(e));
    }
    return obj;
  },

  create(base?: DeepPartial<Txs>): Txs {
    return Txs.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Txs>): Txs {
    const message = createBaseTxs();
    message.txs = object.txs?.map((e) => e) || [];
    return message;
  },
};

function createBaseHaveTx(): HaveTx {
  return { tx_key: new Uint8Array(0) };
}

export const HaveTx = {
  $type: "cometbft.mempool.v2.HaveTx" as const,

  encode(message: HaveTx, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.tx_key.length !== 0) {
      writer.uint32(10).bytes(message.tx_key);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): HaveTx {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHaveTx();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.tx_key = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HaveTx {
    return { tx_key: isSet(object.tx_key) ? bytesFromBase64(object.tx_key) : new Uint8Array(0) };
  },

  toJSON(message: HaveTx): unknown {
    const obj: any = {};
    if (message.tx_key !== undefined) {
      obj.tx_key = base64FromBytes(message.tx_key);
    }
    return obj;
  },

  create(base?: DeepPartial<HaveTx>): HaveTx {
    return HaveTx.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HaveTx>): HaveTx {
    const message = createBaseHaveTx();
    message.tx_key = object.tx_key ?? new Uint8Array(0);
    return message;
  },
};

function createBaseResetRoute(): ResetRoute {
  return {};
}

export const ResetRoute = {
  $type: "cometbft.mempool.v2.ResetRoute" as const,

  encode(_: ResetRoute, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ResetRoute {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetRoute();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ResetRoute {
    return {};
  },

  toJSON(_: ResetRoute): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<ResetRoute>): ResetRoute {
    return ResetRoute.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ResetRoute>): ResetRoute {
    const message = createBaseResetRoute();
    return message;
  },
};

function createBaseMessage(): Message {
  return { txs: undefined, have_tx: undefined, reset_route: undefined };
}

export const Message = {
  $type: "cometbft.mempool.v2.Message" as const,

  encode(message: Message, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.txs !== undefined) {
      Txs.encode(message.txs, writer.uint32(10).fork()).ldelim();
    }
    if (message.have_tx !== undefined) {
      HaveTx.encode(message.have_tx, writer.uint32(18).fork()).ldelim();
    }
    if (message.reset_route !== undefined) {
      ResetRoute.encode(message.reset_route, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Message {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.txs = Txs.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.have_tx = HaveTx.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.reset_route = ResetRoute.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Message {
    return {
      txs: isSet(object.txs) ? Txs.fromJSON(object.txs) : undefined,
      have_tx: isSet(object.have_tx) ? HaveTx.fromJSON(object.have_tx) : undefined,
      reset_route: isSet(object.reset_route) ? ResetRoute.fromJSON(object.reset_route) : undefined,
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.txs !== undefined) {
      obj.txs = Txs.toJSON(message.txs);
    }
    if (message.have_tx !== undefined) {
      obj.have_tx = HaveTx.toJSON(message.have_tx);
    }
    if (message.reset_route !== undefined) {
      obj.reset_route = ResetRoute.toJSON(message.reset_route);
    }
    return obj;
  },

  create(base?: DeepPartial<Message>): Message {
    return Message.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Message>): Message {
    const message = createBaseMessage();
    message.txs = (object.txs !== undefined && object.txs !== null) ? Txs.fromPartial(object.txs) : undefined;
    message.have_tx = (object.have_tx !== undefined && object.have_tx !== null)
      ? HaveTx.fromPartial(object.have_tx)
      : undefined;
    message.reset_route = (object.reset_route !== undefined && object.reset_route !== null)
      ? ResetRoute.fromPartial(object.reset_route)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
