// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: cometbft/state/v1beta3/types.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Timestamp } from "../../../google/protobuf/timestamp";
import { ValidatorUpdate } from "../../abci/v1beta1/types";
import { Event } from "../../abci/v1beta2/types";
import { ExecTxResult, ResponseFinalizeBlock } from "../../abci/v1beta3/types";
import { ConsensusParams } from "../../types/v1/params";
import { BlockID } from "../../types/v1beta1/types";
import { ValidatorSet } from "../../types/v1beta1/validator";
import { Version } from "../v1beta1/types";

/**
 * LegacyABCIResponses retains the responses
 * of the legacy ABCI calls during block processing.
 * Note ReponseDeliverTx is renamed to ExecTxResult but they are semantically the same
 * Kept for backwards compatibility for versions prior to v0.38
 */
export interface LegacyABCIResponses {
  deliver_txs: ExecTxResult[];
  end_block: ResponseEndBlock | undefined;
  begin_block: ResponseBeginBlock | undefined;
}

/**
 * ResponseBeginBlock is kept for backward compatibility for versions prior to v0.38,
 * as it was then defined in the cometbft.abci packages.
 */
export interface ResponseBeginBlock {
  events: Event[];
}

/**
 * ResponseEndBlock is kept for backward compatibility for versions prior to v0.38,
 * its earlier revisions were defined in the cometbft.abci packages.
 * It uses an updated definition for the consensus_param_updates field to keep the
 * generated data types interoperable with the latest protocol.
 */
export interface ResponseEndBlock {
  validator_updates: ValidatorUpdate[];
  consensus_param_updates: ConsensusParams | undefined;
  events: Event[];
}

/** ConsensusParamsInfo represents the latest consensus params, or the last height it changed */
export interface ConsensusParamsInfo {
  consensus_params: ConsensusParams | undefined;
  last_height_changed: string;
}

/** ABCIResponsesInfo retains the responses of the ABCI calls during block processing. */
export interface ABCIResponsesInfo {
  /** Retains the responses of the legacy ABCI calls during block processing. */
  legacy_abci_responses: LegacyABCIResponses | undefined;
  height: string;
  response_finalize_block: ResponseFinalizeBlock | undefined;
}

/** State represents the state of the blockchain. */
export interface State {
  version:
    | Version
    | undefined;
  /** immutable */
  chain_id: string;
  initial_height: string;
  /** LastBlockHeight=0 at genesis (ie. block(H=0) does not exist) */
  last_block_height: string;
  last_block_id: BlockID | undefined;
  last_block_time:
    | Date
    | undefined;
  /**
   * LastValidators is used to validate block.LastCommit.
   * Validators are persisted to the database separately every time they change,
   * so we can query for historical validator sets.
   * Note that if s.LastBlockHeight causes a valset change,
   * we set s.LastHeightValidatorsChanged = s.LastBlockHeight + 1 + 1
   * Extra +1 due to nextValSet delay.
   */
  next_validators: ValidatorSet | undefined;
  validators: ValidatorSet | undefined;
  last_validators: ValidatorSet | undefined;
  last_height_validators_changed: string;
  /**
   * Consensus parameters used for validating blocks.
   * Changes returned by EndBlock and updated after Commit.
   */
  consensus_params: ConsensusParams | undefined;
  last_height_consensus_params_changed: string;
  /** Merkle root of the results from executing prev block */
  last_results_hash: Uint8Array;
  /** the latest AppHash we've received from calling abci.Commit() */
  app_hash: Uint8Array;
}

function createBaseLegacyABCIResponses(): LegacyABCIResponses {
  return { deliver_txs: [], end_block: undefined, begin_block: undefined };
}

export const LegacyABCIResponses = {
  $type: "cometbft.state.v1beta3.LegacyABCIResponses" as const,

  encode(message: LegacyABCIResponses, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.deliver_txs) {
      ExecTxResult.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.end_block !== undefined) {
      ResponseEndBlock.encode(message.end_block, writer.uint32(18).fork()).ldelim();
    }
    if (message.begin_block !== undefined) {
      ResponseBeginBlock.encode(message.begin_block, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LegacyABCIResponses {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLegacyABCIResponses();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.deliver_txs.push(ExecTxResult.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.end_block = ResponseEndBlock.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.begin_block = ResponseBeginBlock.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LegacyABCIResponses {
    return {
      deliver_txs: globalThis.Array.isArray(object?.deliver_txs)
        ? object.deliver_txs.map((e: any) => ExecTxResult.fromJSON(e))
        : [],
      end_block: isSet(object.end_block) ? ResponseEndBlock.fromJSON(object.end_block) : undefined,
      begin_block: isSet(object.begin_block) ? ResponseBeginBlock.fromJSON(object.begin_block) : undefined,
    };
  },

  toJSON(message: LegacyABCIResponses): unknown {
    const obj: any = {};
    if (message.deliver_txs?.length) {
      obj.deliver_txs = message.deliver_txs.map((e) => ExecTxResult.toJSON(e));
    }
    if (message.end_block !== undefined) {
      obj.end_block = ResponseEndBlock.toJSON(message.end_block);
    }
    if (message.begin_block !== undefined) {
      obj.begin_block = ResponseBeginBlock.toJSON(message.begin_block);
    }
    return obj;
  },

  create(base?: DeepPartial<LegacyABCIResponses>): LegacyABCIResponses {
    return LegacyABCIResponses.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LegacyABCIResponses>): LegacyABCIResponses {
    const message = createBaseLegacyABCIResponses();
    message.deliver_txs = object.deliver_txs?.map((e) => ExecTxResult.fromPartial(e)) || [];
    message.end_block = (object.end_block !== undefined && object.end_block !== null)
      ? ResponseEndBlock.fromPartial(object.end_block)
      : undefined;
    message.begin_block = (object.begin_block !== undefined && object.begin_block !== null)
      ? ResponseBeginBlock.fromPartial(object.begin_block)
      : undefined;
    return message;
  },
};

function createBaseResponseBeginBlock(): ResponseBeginBlock {
  return { events: [] };
}

export const ResponseBeginBlock = {
  $type: "cometbft.state.v1beta3.ResponseBeginBlock" as const,

  encode(message: ResponseBeginBlock, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.events) {
      Event.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ResponseBeginBlock {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponseBeginBlock();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.events.push(Event.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResponseBeginBlock {
    return { events: globalThis.Array.isArray(object?.events) ? object.events.map((e: any) => Event.fromJSON(e)) : [] };
  },

  toJSON(message: ResponseBeginBlock): unknown {
    const obj: any = {};
    if (message.events?.length) {
      obj.events = message.events.map((e) => Event.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ResponseBeginBlock>): ResponseBeginBlock {
    return ResponseBeginBlock.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ResponseBeginBlock>): ResponseBeginBlock {
    const message = createBaseResponseBeginBlock();
    message.events = object.events?.map((e) => Event.fromPartial(e)) || [];
    return message;
  },
};

function createBaseResponseEndBlock(): ResponseEndBlock {
  return { validator_updates: [], consensus_param_updates: undefined, events: [] };
}

export const ResponseEndBlock = {
  $type: "cometbft.state.v1beta3.ResponseEndBlock" as const,

  encode(message: ResponseEndBlock, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.validator_updates) {
      ValidatorUpdate.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.consensus_param_updates !== undefined) {
      ConsensusParams.encode(message.consensus_param_updates, writer.uint32(18).fork()).ldelim();
    }
    for (const v of message.events) {
      Event.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ResponseEndBlock {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponseEndBlock();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.validator_updates.push(ValidatorUpdate.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.consensus_param_updates = ConsensusParams.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.events.push(Event.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResponseEndBlock {
    return {
      validator_updates: globalThis.Array.isArray(object?.validator_updates)
        ? object.validator_updates.map((e: any) => ValidatorUpdate.fromJSON(e))
        : [],
      consensus_param_updates: isSet(object.consensus_param_updates)
        ? ConsensusParams.fromJSON(object.consensus_param_updates)
        : undefined,
      events: globalThis.Array.isArray(object?.events) ? object.events.map((e: any) => Event.fromJSON(e)) : [],
    };
  },

  toJSON(message: ResponseEndBlock): unknown {
    const obj: any = {};
    if (message.validator_updates?.length) {
      obj.validator_updates = message.validator_updates.map((e) => ValidatorUpdate.toJSON(e));
    }
    if (message.consensus_param_updates !== undefined) {
      obj.consensus_param_updates = ConsensusParams.toJSON(message.consensus_param_updates);
    }
    if (message.events?.length) {
      obj.events = message.events.map((e) => Event.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ResponseEndBlock>): ResponseEndBlock {
    return ResponseEndBlock.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ResponseEndBlock>): ResponseEndBlock {
    const message = createBaseResponseEndBlock();
    message.validator_updates = object.validator_updates?.map((e) => ValidatorUpdate.fromPartial(e)) || [];
    message.consensus_param_updates =
      (object.consensus_param_updates !== undefined && object.consensus_param_updates !== null)
        ? ConsensusParams.fromPartial(object.consensus_param_updates)
        : undefined;
    message.events = object.events?.map((e) => Event.fromPartial(e)) || [];
    return message;
  },
};

function createBaseConsensusParamsInfo(): ConsensusParamsInfo {
  return { consensus_params: undefined, last_height_changed: "0" };
}

export const ConsensusParamsInfo = {
  $type: "cometbft.state.v1beta3.ConsensusParamsInfo" as const,

  encode(message: ConsensusParamsInfo, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.consensus_params !== undefined) {
      ConsensusParams.encode(message.consensus_params, writer.uint32(10).fork()).ldelim();
    }
    if (message.last_height_changed !== "0") {
      writer.uint32(16).int64(message.last_height_changed);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ConsensusParamsInfo {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConsensusParamsInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.consensus_params = ConsensusParams.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.last_height_changed = longToString(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConsensusParamsInfo {
    return {
      consensus_params: isSet(object.consensus_params) ? ConsensusParams.fromJSON(object.consensus_params) : undefined,
      last_height_changed: isSet(object.last_height_changed) ? globalThis.String(object.last_height_changed) : "0",
    };
  },

  toJSON(message: ConsensusParamsInfo): unknown {
    const obj: any = {};
    if (message.consensus_params !== undefined) {
      obj.consensus_params = ConsensusParams.toJSON(message.consensus_params);
    }
    if (message.last_height_changed !== undefined) {
      obj.last_height_changed = message.last_height_changed;
    }
    return obj;
  },

  create(base?: DeepPartial<ConsensusParamsInfo>): ConsensusParamsInfo {
    return ConsensusParamsInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ConsensusParamsInfo>): ConsensusParamsInfo {
    const message = createBaseConsensusParamsInfo();
    message.consensus_params = (object.consensus_params !== undefined && object.consensus_params !== null)
      ? ConsensusParams.fromPartial(object.consensus_params)
      : undefined;
    message.last_height_changed = object.last_height_changed ?? "0";
    return message;
  },
};

function createBaseABCIResponsesInfo(): ABCIResponsesInfo {
  return { legacy_abci_responses: undefined, height: "0", response_finalize_block: undefined };
}

export const ABCIResponsesInfo = {
  $type: "cometbft.state.v1beta3.ABCIResponsesInfo" as const,

  encode(message: ABCIResponsesInfo, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.legacy_abci_responses !== undefined) {
      LegacyABCIResponses.encode(message.legacy_abci_responses, writer.uint32(10).fork()).ldelim();
    }
    if (message.height !== "0") {
      writer.uint32(16).int64(message.height);
    }
    if (message.response_finalize_block !== undefined) {
      ResponseFinalizeBlock.encode(message.response_finalize_block, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ABCIResponsesInfo {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseABCIResponsesInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.legacy_abci_responses = LegacyABCIResponses.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.height = longToString(reader.int64() as Long);
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.response_finalize_block = ResponseFinalizeBlock.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ABCIResponsesInfo {
    return {
      legacy_abci_responses: isSet(object.legacy_abci_responses)
        ? LegacyABCIResponses.fromJSON(object.legacy_abci_responses)
        : undefined,
      height: isSet(object.height) ? globalThis.String(object.height) : "0",
      response_finalize_block: isSet(object.response_finalize_block)
        ? ResponseFinalizeBlock.fromJSON(object.response_finalize_block)
        : undefined,
    };
  },

  toJSON(message: ABCIResponsesInfo): unknown {
    const obj: any = {};
    if (message.legacy_abci_responses !== undefined) {
      obj.legacy_abci_responses = LegacyABCIResponses.toJSON(message.legacy_abci_responses);
    }
    if (message.height !== undefined) {
      obj.height = message.height;
    }
    if (message.response_finalize_block !== undefined) {
      obj.response_finalize_block = ResponseFinalizeBlock.toJSON(message.response_finalize_block);
    }
    return obj;
  },

  create(base?: DeepPartial<ABCIResponsesInfo>): ABCIResponsesInfo {
    return ABCIResponsesInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ABCIResponsesInfo>): ABCIResponsesInfo {
    const message = createBaseABCIResponsesInfo();
    message.legacy_abci_responses =
      (object.legacy_abci_responses !== undefined && object.legacy_abci_responses !== null)
        ? LegacyABCIResponses.fromPartial(object.legacy_abci_responses)
        : undefined;
    message.height = object.height ?? "0";
    message.response_finalize_block =
      (object.response_finalize_block !== undefined && object.response_finalize_block !== null)
        ? ResponseFinalizeBlock.fromPartial(object.response_finalize_block)
        : undefined;
    return message;
  },
};

function createBaseState(): State {
  return {
    version: undefined,
    chain_id: "",
    initial_height: "0",
    last_block_height: "0",
    last_block_id: undefined,
    last_block_time: undefined,
    next_validators: undefined,
    validators: undefined,
    last_validators: undefined,
    last_height_validators_changed: "0",
    consensus_params: undefined,
    last_height_consensus_params_changed: "0",
    last_results_hash: new Uint8Array(0),
    app_hash: new Uint8Array(0),
  };
}

export const State = {
  $type: "cometbft.state.v1beta3.State" as const,

  encode(message: State, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.version !== undefined) {
      Version.encode(message.version, writer.uint32(10).fork()).ldelim();
    }
    if (message.chain_id !== "") {
      writer.uint32(18).string(message.chain_id);
    }
    if (message.initial_height !== "0") {
      writer.uint32(112).int64(message.initial_height);
    }
    if (message.last_block_height !== "0") {
      writer.uint32(24).int64(message.last_block_height);
    }
    if (message.last_block_id !== undefined) {
      BlockID.encode(message.last_block_id, writer.uint32(34).fork()).ldelim();
    }
    if (message.last_block_time !== undefined) {
      Timestamp.encode(toTimestamp(message.last_block_time), writer.uint32(42).fork()).ldelim();
    }
    if (message.next_validators !== undefined) {
      ValidatorSet.encode(message.next_validators, writer.uint32(50).fork()).ldelim();
    }
    if (message.validators !== undefined) {
      ValidatorSet.encode(message.validators, writer.uint32(58).fork()).ldelim();
    }
    if (message.last_validators !== undefined) {
      ValidatorSet.encode(message.last_validators, writer.uint32(66).fork()).ldelim();
    }
    if (message.last_height_validators_changed !== "0") {
      writer.uint32(72).int64(message.last_height_validators_changed);
    }
    if (message.consensus_params !== undefined) {
      ConsensusParams.encode(message.consensus_params, writer.uint32(82).fork()).ldelim();
    }
    if (message.last_height_consensus_params_changed !== "0") {
      writer.uint32(88).int64(message.last_height_consensus_params_changed);
    }
    if (message.last_results_hash.length !== 0) {
      writer.uint32(98).bytes(message.last_results_hash);
    }
    if (message.app_hash.length !== 0) {
      writer.uint32(106).bytes(message.app_hash);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): State {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.version = Version.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.chain_id = reader.string();
          continue;
        case 14:
          if (tag !== 112) {
            break;
          }

          message.initial_height = longToString(reader.int64() as Long);
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.last_block_height = longToString(reader.int64() as Long);
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.last_block_id = BlockID.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.last_block_time = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.next_validators = ValidatorSet.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.validators = ValidatorSet.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.last_validators = ValidatorSet.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.last_height_validators_changed = longToString(reader.int64() as Long);
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.consensus_params = ConsensusParams.decode(reader, reader.uint32());
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.last_height_consensus_params_changed = longToString(reader.int64() as Long);
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.last_results_hash = reader.bytes();
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.app_hash = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): State {
    return {
      version: isSet(object.version) ? Version.fromJSON(object.version) : undefined,
      chain_id: isSet(object.chain_id) ? globalThis.String(object.chain_id) : "",
      initial_height: isSet(object.initial_height) ? globalThis.String(object.initial_height) : "0",
      last_block_height: isSet(object.last_block_height) ? globalThis.String(object.last_block_height) : "0",
      last_block_id: isSet(object.last_block_id) ? BlockID.fromJSON(object.last_block_id) : undefined,
      last_block_time: isSet(object.last_block_time) ? fromJsonTimestamp(object.last_block_time) : undefined,
      next_validators: isSet(object.next_validators) ? ValidatorSet.fromJSON(object.next_validators) : undefined,
      validators: isSet(object.validators) ? ValidatorSet.fromJSON(object.validators) : undefined,
      last_validators: isSet(object.last_validators) ? ValidatorSet.fromJSON(object.last_validators) : undefined,
      last_height_validators_changed: isSet(object.last_height_validators_changed)
        ? globalThis.String(object.last_height_validators_changed)
        : "0",
      consensus_params: isSet(object.consensus_params) ? ConsensusParams.fromJSON(object.consensus_params) : undefined,
      last_height_consensus_params_changed: isSet(object.last_height_consensus_params_changed)
        ? globalThis.String(object.last_height_consensus_params_changed)
        : "0",
      last_results_hash: isSet(object.last_results_hash)
        ? bytesFromBase64(object.last_results_hash)
        : new Uint8Array(0),
      app_hash: isSet(object.app_hash) ? bytesFromBase64(object.app_hash) : new Uint8Array(0),
    };
  },

  toJSON(message: State): unknown {
    const obj: any = {};
    if (message.version !== undefined) {
      obj.version = Version.toJSON(message.version);
    }
    if (message.chain_id !== undefined) {
      obj.chain_id = message.chain_id;
    }
    if (message.initial_height !== undefined) {
      obj.initial_height = message.initial_height;
    }
    if (message.last_block_height !== undefined) {
      obj.last_block_height = message.last_block_height;
    }
    if (message.last_block_id !== undefined) {
      obj.last_block_id = BlockID.toJSON(message.last_block_id);
    }
    if (message.last_block_time !== undefined) {
      obj.last_block_time = message.last_block_time.toISOString();
    }
    if (message.next_validators !== undefined) {
      obj.next_validators = ValidatorSet.toJSON(message.next_validators);
    }
    if (message.validators !== undefined) {
      obj.validators = ValidatorSet.toJSON(message.validators);
    }
    if (message.last_validators !== undefined) {
      obj.last_validators = ValidatorSet.toJSON(message.last_validators);
    }
    if (message.last_height_validators_changed !== undefined) {
      obj.last_height_validators_changed = message.last_height_validators_changed;
    }
    if (message.consensus_params !== undefined) {
      obj.consensus_params = ConsensusParams.toJSON(message.consensus_params);
    }
    if (message.last_height_consensus_params_changed !== undefined) {
      obj.last_height_consensus_params_changed = message.last_height_consensus_params_changed;
    }
    if (message.last_results_hash !== undefined) {
      obj.last_results_hash = base64FromBytes(message.last_results_hash);
    }
    if (message.app_hash !== undefined) {
      obj.app_hash = base64FromBytes(message.app_hash);
    }
    return obj;
  },

  create(base?: DeepPartial<State>): State {
    return State.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<State>): State {
    const message = createBaseState();
    message.version = (object.version !== undefined && object.version !== null)
      ? Version.fromPartial(object.version)
      : undefined;
    message.chain_id = object.chain_id ?? "";
    message.initial_height = object.initial_height ?? "0";
    message.last_block_height = object.last_block_height ?? "0";
    message.last_block_id = (object.last_block_id !== undefined && object.last_block_id !== null)
      ? BlockID.fromPartial(object.last_block_id)
      : undefined;
    message.last_block_time = object.last_block_time ?? undefined;
    message.next_validators = (object.next_validators !== undefined && object.next_validators !== null)
      ? ValidatorSet.fromPartial(object.next_validators)
      : undefined;
    message.validators = (object.validators !== undefined && object.validators !== null)
      ? ValidatorSet.fromPartial(object.validators)
      : undefined;
    message.last_validators = (object.last_validators !== undefined && object.last_validators !== null)
      ? ValidatorSet.fromPartial(object.last_validators)
      : undefined;
    message.last_height_validators_changed = object.last_height_validators_changed ?? "0";
    message.consensus_params = (object.consensus_params !== undefined && object.consensus_params !== null)
      ? ConsensusParams.fromPartial(object.consensus_params)
      : undefined;
    message.last_height_consensus_params_changed = object.last_height_consensus_params_changed ?? "0";
    message.last_results_hash = object.last_results_hash ?? new Uint8Array(0);
    message.app_hash = object.app_hash ?? new Uint8Array(0);
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000).toString();
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToString(long: Long) {
  return long.toString();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
